"use client";

import { Card } from "@/components/ui/card";

interface WarehouseRecommendation {
  id: string;
  from_warehouse_id: string;
  to_warehouse_id: string;
  quantity: number;
  confidence: number | string;
  status: string;
  reason?: string | null;
}

interface WarehouseRebalanceDashboardProps {
  recommendations: WarehouseRecommendation[];
}

export function WarehouseRebalanceDashboard({
  recommendations,
}: WarehouseRebalanceDashboardProps) {
  return (
    <Card className="rounded-xl border-border dark:border-dark-border p-4">
      <h3 className="text-sm font-semibold text-text-1 dark:text-dark-text-1">
        Warehouse Rebalancing
      </h3>
      <p className="mt-1 text-xs text-text-3 dark:text-dark-text-3">
        Transfer recommendations generated by warehouse agents
      </p>
      <div className="mt-3 space-y-2">
        {recommendations.length === 0 ? (
          <p className="text-xs text-text-3 dark:text-dark-text-3">
            No recommendations yet.
          </p>
        ) : (
          recommendations.slice(0, 5).map((item) => (
            <div
              key={item.id}
              className="rounded-lg border border-border dark:border-dark-border px-3 py-2"
            >
              <p className="text-xs font-medium text-text-1 dark:text-dark-text-1">
                {item.from_warehouse_id} → {item.to_warehouse_id}
              </p>
              <p className="text-xs text-text-3 dark:text-dark-text-3">
                Qty {item.quantity} • Confidence {Number(item.confidence).toFixed(2)} •{" "}
                {item.status}
              </p>
            </div>
          ))
        )}
      </div>
    </Card>
  );
}
